### ISSUE TITLE
Meta tags and Og images

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/tvhunt-web#2]
Meta tags
- [x] Meta tags on main (default ones)
- [x] Meta tags on sub pages (change title to "video title - LOL Hunt")
- [x] Meta tags on my votes (change title to "My Votes - LOL Hunt")
- [x] Meta tags on shared videos (change title to "Shared Videos - LOL Hunt")

Og images
- [x] Main page: Should be default ones (not the first video of the day)
- [x] Sub page: Should be video thumbnail

**Comment by ggomaeng** [comment]
@cyh76507707 Could you please list the title and description for each page?

**Comment by sydneyitguy** [comment]
Main title: TV Hunt - Daily top chart for videos
Main description: TV Hunt is a daily top chart for videos. Anyone can simply share a cool video that they found today. No sign-ups are required.

- Sub page: video title - TV Hunt
- My Uploads: My Uploads - TV Hunt
- My Votes: My Votes - TV Hunt

**Comment by ggomaeng** [comment]
What's a good number of letter count to truncate the video title?

**Comment by sydneyitguy** [comment]
I don’t think we need to truncate the titles ourselves in this case. 

Google only shows certain number of characters for title (70) and description (160), but there’s no hard limit technically. So let’s just leave full string for google to truncate.

**Comment by sydneyitguy** [comment]
OG title, description, images are not set correctly on video pages and sub pages

https://media.discordapp.net/attachments/424120765231923201/647609109704605706/unknown.png?width=942&height=669

![image](https://user-images.githubusercontent.com/1332279/69470789-5946cd80-0ddc-11ea-8528-0520a63d4b29.png)

**Comment by ggomaeng** [comment]
Should be resolved in 449c2027
